# This is a basic workflow to help you get started with Actions
name: Windows RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Enable RDP Access
      run: |
        net user runneradmin 12345 /add
        net localgroup administrators runneradmin /add
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        echo "IP Address:" $env:COMPUTERNAME
